spring.application.name=backend


spring.datasource.url=jdbc:postgresql://localhost:5432/streetviz3d
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

app.nginx.base-url=http://localhost:65
app.nginx.upload-dir=D:/nginx/nginx-1.26.2/StreetViz3D/auth

app.user-model-storage.base-url=http://localhost:65/auth/model
app.user-model-storage.upload-dir=D:/nginx/nginx-1.26.2/StreetViz3D/auth/model

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB